#==========================================================================
# Description: MatrixBuild D3588 Armbian Image
#==========================================================================

name: MatrixBuild D3588 Armbian Image

on:
  repository_dispatch:
  workflow_dispatch:


env:
  TZ: America/New_York
  ROOTFS_SCRIPT: compile-kernel/tools/script/armbian_rootfs.sh

jobs:
  build:
    # using ubuntu 22.04 virtual machine environment
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # 基础矩阵：发行版列表
        set_release: [ bullseye, bookworm, jammy, noble ]
        set_desktop: [ cli, gnome, xfce ]

    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q) 2>/dev/null
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install python2 python2-dev python-is-python3 squashfs-tools $(curl -fsSL https://tinyurl.com/ubuntu2204-build-armbian)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Create simulated physical disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner.runner /builder
          df -Th

      - name: Download D3588 Uboot and Kernel code
        id: down_d3588
        working-directory: /builder/
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        run: |
          df -hT ${PWD}
          git clone --recursive --single-branch --branch=master https://github.com/yifengyou/d3588.git d3588.git
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compile D3588 Uboot and Kernel code
        id: compile_d3588
        working-directory: /builder/d3588.git
        if: ${{ steps.down_d3588.outputs.status }} == 'success' && !cancelled()
        run: |
          ls -alh
          du -sh *
          ./build.sh
          ls -alh rockdev
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Download armbian source code
        id: down_armbian
        working-directory: /builder/
        if: ${{ steps.compile_d3588.outputs.status }} == 'success' && !cancelled()
        run: |
          df -hT ${PWD}
          git clone -q --single-branch --depth=1 --branch=main https://github.com/armbian/build.git armbian.git
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compile Armbian [ ${{ matrix.set_release }} ] [ ${{ matrix.set_desktop }} ]
        id: compile_armbian
        working-directory: /builder/armbian.git
        if: ${{ steps.down_armbian.outputs.status }} == 'success' && !cancelled()
        run: |
          # set up build tag
          echo "build_tag=Armbian_D3588_${{ matrix.set_release }}_${{ matrix.set_desktop }}" >> ${GITHUB_OUTPUT}

          if [ "${{ matrix.set_desktop }}" == "cli" ] ; then
            BUILD_DESKTOP="BUILD_DESKTOP=no"
          else
            BUILD_DESKTOP=" \
                BUILD_DESKTOP=yes \
                DESKTOP_APPGROUPS_SELECTED=remote_desktop \
                DESKTOP_ENVIRONMENT=${{ matrix.set_desktop }} \
                DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base"
          fi
          # BRANCH=edge    : newest kernel such as 6.10
          # BRANCH=current : stable kernel such as 6.6
          # BRANCH=legacy  : vendor kernel rockchip 5.10
          ./compile.sh RELEASE=${{ matrix.set_release }} \
                       BOARD=nanopct6 \
                       BRANCH=current\
                       BUILD_MINIMAL=no \
                       BUILD_ONLY=default \
                       HOST=armbian \
                       ${BUILD_DESKTOP} \
                       EXPERT=yes \
                       KERNEL_CONFIGURE=no \
                       COMPRESS_OUTPUTIMAGE="sha,img,xz" \
                       VENDOR="Armbian" \
                       SHARE_LOG=yes
          ls -alh /builder/armbian.git/output/images/
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Generate rootfs image
        id: generate_rootfs
        working-directory: /builder/
        if: ${{ steps.compile_armbian.outputs.status }} == 'success' && !cancelled()
        run: |
          # 创建目录
          mkdir -p /builder/d3588.git/tools/RKDevTool/rockdev/image/
          mkdir -p /builder/d3588.git/rockdev
          mkdir -p /builder/d3588.git/release
          # archive modules
          cd /builder/d3588.git/rockdev && tar -zcvf modules.tar.gz modules && rm -rf modules
          # generate rootfs.img in /builder/armbian.git/output/images/
          chmod +x /builder/d3588.git/extract-rootfs-from-armbian.sh
          /builder/d3588.git/extract-rootfs-from-armbian.sh /builder/armbian.git/output/images/
          mv /builder/armbian.git/output/images/rootfs.img /builder/d3588.git/rockdev/
          # generate all in one updateable update.img
          chmod +x /builder/d3588.git/tools/afptool
          chmod +x /builder/d3588.git/tools/rkImageMaker
          cd /builder/d3588.git/rockdev && \
              /builder/d3588.git/tools/afptool -pack . temp.img && \
              /builder/d3588.git/tools/rkImageMaker -RK3588 MiniLoaderAll.bin temp.img update.img -os_type:androidos
          # release update.img.squashfs
          cd /builder/d3588.git/rockdev && mksquashfs update.img  /builder/d3588.git/release/update.img.squashfs

          mv /builder/d3588.git/rockdev/boot.img             /builder/d3588.git/tools/RKDevTool/rockdev/image/
          mv /builder/d3588.git/rockdev/MiniLoaderAll.bin    /builder/d3588.git/tools/RKDevTool/rockdev/image/
          mv /builder/d3588.git/rockdev/modules.tar.gz       /builder/d3588.git/tools/RKDevTool/rockdev/image/
          mv /builder/d3588.git/rockdev/parameter.txt        /builder/d3588.git/tools/RKDevTool/rockdev/image/
          mv /builder/d3588.git/rockdev/rootfs.img           /builder/d3588.git/tools/RKDevTool/rockdev/image/
          mv /builder/d3588.git/rockdev/uboot.img            /builder/d3588.git/tools/RKDevTool/rockdev/image/
          mv /builder/d3588.git/rockdev/misc.img             /builder/d3588.git/tools/RKDevTool/rockdev/image/
          mv /builder/d3588.git/rockdev/modules.tar.gz       /builder/d3588.git/tools/RKDevTool/rockdev/image/
          mv /builder/d3588.git/rockdev/package-file         /builder/d3588.git/tools/RKDevTool/rockdev/image/
          mv /builder/d3588.git/rockdev/recovery.img         /builder/d3588.git/tools/RKDevTool/rockdev/image/
          mv /builder/d3588.git/rockdev/oem.img              /builder/d3588.git/tools/RKDevTool/rockdev/image/
          # release rockdev.squashfs
          cd /builder/d3588.git/tools/ && mksquashfs  RKDevTool  /builder/d3588.git/release/rockdev.squashfs
          # release Armbian files
          mv /builder/armbian.git/output/images/Armbian* /builder/d3588.git/release
          # release image
          mv /builder/d3588.git/tools/RKDevTool/rockdev/image/boot.img             /builder/d3588.git/release/
          mv /builder/d3588.git/tools/RKDevTool/rockdev/image/MiniLoaderAll.bin    /builder/d3588.git/release/
          mv /builder/d3588.git/tools/RKDevTool/rockdev/image/modules.tar.gz       /builder/d3588.git/release/
          mv /builder/d3588.git/tools/RKDevTool/rockdev/image/parameter.txt        /builder/d3588.git/release/
          mv /builder/d3588.git/tools/RKDevTool/rockdev/image/uboot.img            /builder/d3588.git/release/
          mv /builder/d3588.git/tools/RKDevTool/rockdev/image/misc.img             /builder/d3588.git/release/
          mv /builder/d3588.git/tools/RKDevTool/rockdev/image/modules.tar.gz       /builder/d3588.git/release/
          mv /builder/d3588.git/tools/RKDevTool/rockdev/image/package-file         /builder/d3588.git/release/
          mv /builder/d3588.git/tools/RKDevTool/rockdev/image/recovery.img         /builder/d3588.git/release/
          mv /builder/d3588.git/tools/RKDevTool/rockdev/image/oem.img              /builder/d3588.git/release/
          # release rootfs.img.squashfs
          cd /builder/d3588.git/tools/RKDevTool/rockdev/image/ && mksquashfs rootfs.img  /builder/d3588.git/release/rootfs.img.squashfs
          # show all files
          ls -alh /builder/d3588.git/release/
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload D3588 image to Release
        uses: ncipollo/release-action@main
        if: ${{ steps.generate_rootfs.outputs.status }} == 'success' && !cancelled()
        with:
          tag: ${{ steps.compile_armbian.outputs.build_tag }}
          artifacts: /builder/d3588.git/release/
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### Armbian Image for D3588 information
            - Default username: root
            - Default password: 123
            ### rockdev.squashfs
            - boot.img
            - misc.img
            - recovery.img
            - rootfs.img
            - uboot.img
            - oem.img
            - config.cfg
            - MiniLoaderAll.bin
            - parameter.txt
            - package-file
            ### update.img.squashfs
            - updateable rockdev img
            ### rootfs.img.squashfs
            - only rootfs.img with squashfs archive






